# Generated by Django 4.0 on 2022-01-11 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MroInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, null=True)),
                ('text', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, null=True)),
                ('latitude', models.FloatField(help_text='Широта', null=True)),
                ('longitude', models.FloatField(help_text='Долгота', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorckPlace',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, null=True)),
                ('info', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=255, null=True)),
                ('more_info', models.TextField()),
                ('price', models.IntegerField(help_text='цена консультации', null=True)),
                ('photo', models.ImageField(upload_to='doctor_photo')),
                ('For_child', models.BooleanField(null=True)),
                ('speciality', models.ManyToManyField(to='index.Speciality')),
                ('town', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.town')),
                ('worck_place', models.ManyToManyField(to='index.WorckPlace')),
            ],
        ),
    ]
