# Generated by Django 4.0 on 2022-01-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_speciality_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
