# Generated by Django 4.0 on 2022-01-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_speciality_id_alter_speciality_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worckplace',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
