# Generated by Django 4.0 on 2022-01-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_doctor_description_alter_doctor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='slug',
            field=models.SlugField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
