# Generated by Django 4.0 on 2022-02-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_town_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='info',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='more_info',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='price',
            field=models.IntegerField(default=1, help_text='цена консультации', null=True),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.category')),
            ],
        ),
    ]
