# Generated by Django 4.0 on 2022-01-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_doctor_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='price',
            field=models.IntegerField(default=1, help_text='цена консультации', null=True),
        ),
    ]
