# Generated by Django 4.0 on 2022-01-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_alter_doctor_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=60, null=True, unique=True),
        ),
    ]
