# Generated by Django 4.0 on 2022-01-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_alter_doctor_info_alter_doctor_more_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='info',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='more_info',
            field=models.TextField(max_length=4000),
        ),
    ]
