# Generated by Django 4.0 on 2022-02-06 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_category_alter_doctor_info_alter_doctor_more_info_and_more'),
        ('index', '0012_alter_doctor_info_alter_doctor_more_info'),
    ]

    operations = [
    ]
