# Generated by Django 4.0 on 2022-02-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_merge_20220206_2014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageWorckPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(null=True, upload_to='medical_photo/%Y/%m/%d/')),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='worckplace',
            name='address',
            field=models.CharField(default='Ukraine', max_length=255),
        ),
        migrations.AddField(
            model_name='worckplace',
            name='branch',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='worckplace',
            name='description',
            field=models.TextField(max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='worckplace',
            name='logo',
            field=models.ImageField(max_length=255, null=True, upload_to='medical_logo/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='worckplace',
            name='phone',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='worckplace',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='worckplace',
            name='worck_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='worckplace',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.imageworckplace'),
        ),
    ]
