# Generated by Django 4.0 on 2022-02-09 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_imageworckplace_worckplace_address_worckplace_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worckplace',
            name='photo',
        ),
        migrations.AddField(
            model_name='worckplace',
            name='photo',
            field=models.ManyToManyField(null=True, to='index.ImageWorckPlace'),
        ),
    ]
