# Generated by Django 4.0 on 2022-02-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_remove_worckplace_photo_worckplace_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worckplace',
            old_name='address',
            new_name='street',
        ),
        migrations.AddField(
            model_name='worckplace',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.town'),
        ),
        migrations.AlterField(
            model_name='worckplace',
            name='worck_time',
            field=models.JSONField(null=True),
        ),
    ]
