# Generated by Django 4.0 on 2022-02-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_rename_address_worckplace_street_worckplace_town_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageworckplace',
            name='default',
        ),
    ]
