# Generated by Django 4.0 on 2022-02-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_remove_imageworckplace_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worckplace',
            name='photo',
            field=models.ManyToManyField(to='index.ImageWorckPlace'),
        ),
    ]
