# Generated by Django 4.0 on 2022-02-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_alter_worckplace_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageworckplace',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='medical_photo/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='worckplace',
            name='phone',
            field=models.JSONField(max_length=255, null=True),
        ),
    ]
