# Generated by Django 4.0 on 2022-02-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_alter_imageworckplace_image_alter_worckplace_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worckplace',
            name='slug',
            field=models.SlugField(max_length=100, null=True),
        ),
    ]
