# Generated by Django 4.0 on 2022-02-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_alter_worckplace_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageworckplace',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
