# Generated by Django 4.0 on 2022-02-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0022_alter_imageworckplace_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageworckplace',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
