# Generated by Django 4.0 on 2022-02-09 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_alter_imageworckplace_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageworckplace',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
